### ISSUE TITLE
Project added to awesome-ada

### ISSUE THREAD

**Issue by ohenley** [annexi-strayline/Curses#1]
Hi, 

I added your project to [awesome-ada](https://github.com/ohenley/awesome-ada/blob/master/README.md)

If you publish other Ada packages, working and of interest, please consider [contributing](https://github.com/ohenley/awesome-ada/blob/master/CONTRIBUTING.md) to the list. 

Thx.

**Comment by Richard-Wai** [comment]
Hey,

Thanks for picking this up!

We definitely have lots more stuff in the works that will be coming out over the next year and beyond.

I'll be sure to contribute those as well, and thanks for putting this list together!

Cheers.
