### ISSUE TITLE
Integrate as a crate for Alire

### ISSUE THREAD

**Issue by ghost** [annexi-strayline/Curses#3]
Hi. It would be great to have this package ready for use with `alr` from Alire project.

**Comment by Richard-Wai** [comment]
Thanks for your comment. Currently we are working on an alternate package manager (AURA) which we feel is more decentralized and more Ada-like than ALIRE. Once we have used this package manager in production for some time, we will be releasing it to the public as a BSD licensed open source project.

Currently we are focused on integrating Curses (among other useful packages we are using internally) into AURA, and this has slightly different (actually much simpler) semantics to ALIRE.

As Curses is BSD licensed, we welcome anyone who wants to make it a part of ALIRE to do so, but we currently are not intending to do so.
